spring:
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: localhost:22181
          brokers: localhost:29092
  application:
    name: config-client
  profiles:
    active: development
  config:
    import: optional:configserver:http://user:pass@localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh