spring:
  application:
    name: config-client
  profiles:
    active: development
  config:
    import: optional:configserver:http://user:pass@localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh