spring:
  cloud:
    gateway:
      routes:
        - id: aston_route
          uri: https://astontech.com/
          predicates:
            - Path=/
        - id: low_priority_chat_route
          uri: http://localhost:8083
          predicates:
            - Path=/chat
            - name: LdapUser
              args:
                requiredRole: Mentor-Dev
                match: false
        - id: high_priority_chat_route
          uri: http://localhost:8084
          predicates:
            - Path=/chat
            - name: LdapUser
              args:
                requiredRole: Mentor-Dev
                match: true


auth:
  server:
    roles-endpoint: http://localhost:8088/auth/roles